-- delete from USERS;
-- insert into USERS(NAME, EMAIL, PASSWORD, ROLE) values('Ivan', 'ivan@mail.ru', '123', 'ROLE_ADMIN';);
-- insert into USERS(NAME, EMAIL, PASSWORD, ROLE) values('Mark', 'mark@mail.ru', '123', 'ROLE_USER');